# Permalinks
permalink:           pretty

# Setup
title:               Chris J. Maddison
tagline:             Blog
url:                 https://cmaddis.github.io
paginate:            1
baseurl:             "https://cmaddis.github.io"

pages_list:       
  About: '/about'
  Archive: '/archive'
  Academic: 'http://www.stats.ox.ac.uk/~cmaddis/'
  Publications: 'https://scholar.google.ca/citations?user=WjCG3owAAAAJ'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Chris J. Maddison
  url:               http://www.stats.ox.ac.uk/~cmaddis/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cmaddis.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
